version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: random123
      POSTGRES_DB: user_database
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: