CREATE SEQUENCE IF NOT EXISTS app_user_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE app_user
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(255)                             NOT NULL,
    password    VARCHAR(255),
    email       VARCHAR(255)                             NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    provider    VARCHAR(255),
    provider_id VARCHAR(255),
    role        VARCHAR(255),
    CONSTRAINT app_user_pkey PRIMARY KEY (id)
);

CREATE TABLE flyway_schema_history
(
    installed_rank INTEGER       NOT NULL,
    version        VARCHAR(50),
    description    VARCHAR(200)  NOT NULL,
    type           VARCHAR(20)   NOT NULL,
    script         VARCHAR(1000) NOT NULL,
    checksum       INTEGER,
    installed_by   VARCHAR(100)  NOT NULL,
    installed_on   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    execution_time INTEGER       NOT NULL,
    success        BOOLEAN       NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE TABLE permissons
(
    id             INTEGER     NOT NULL,
    permision_desc VARCHAR(255),
    permision_name VARCHAR(56) NOT NULL,
    role_id        INTEGER     NOT NULL,
    CONSTRAINT permissons_pk PRIMARY KEY (id)
);

ALTER TABLE app_user
    ADD CONSTRAINT app_user_email_key UNIQUE (email);

ALTER TABLE app_user
    ADD CONSTRAINT app_user_username_key UNIQUE (username);

CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success);

ALTER TABLE permissons
    ADD CONSTRAINT permissons_app_user_id_fk FOREIGN KEY (role_id) REFERENCES app_user (id) ON DELETE CASCADE;